name: Bump Tex Pin
on:
  workflow_dispatch:
jobs:
  bump-paper-pin:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fregante/setup-git-user@v1
      - name: Update paper submodule to latest on paper branch
        run: |
          git submodule update --init --single-branch paper
          cd tex
          git fetch origin tex
          git checkout origin/tex
          cd ..
          git add tex
          git diff --cached --quiet || git commit -m "bump tex pin"
      - run: git push origin HEAD
